{
  "throws": "Await is illegal outside functions. (1:0)"
}
